# fly.toml app configuration file generated for fly-tigris-speedbench on 2025-07-12T14:30:17+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fly-tigris-speedbench'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '8gb'
  cpu_kind = 'performance'
  cpus = 4

[env]
  S3_BUCKET = 'pnpm-store-test'
